name: Subleq
version: 0.1.0.0
github: "embedded-software-laboratory/SLQISC"
license: BSD-3-Clause
author: "Marcus Völker"
maintainer: "voelker@embedded.rwth-aachen.de"
copyright: "2024 Marcus Völker"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/embedded-software-laboratory/SLQISC#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - LambdaCase
  - ImportQualifiedPost
  - FlexibleInstances

library:
  source-dirs: src

executables:
  assembler:
    main: Main.hs
    source-dirs: app-asm
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Subleq
  simulator:
    main: Main.hs
    source-dirs: app-sim
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Subleq

tests:
  SubleqAssembler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Subleq
